<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo htmlspecialchars($file, ENT_QUOTES, 'UTF-8') ?></title>
    </head>
    <body>
        <dl>
            <dt>Total Lines<dt>
            <dd><?php echo $result['stats']['totalLines'] ?></dd>
            <dt>Executable Lines<dt>
            <dd><?php echo $result['stats']['executableLines'] ?></dd>
            <dt>Lines Executed<dt>
            <dd><?php echo $result['stats']['linesExecuted'] ?></dd>
            <dt>Coverage<dt>
            <dd><?php echo number_format($result['stats']['coverage'] * 100, 1) ?>%</dd>
        </dl>
        <ol>
            <?php foreach ($result['lines'] as $line): ?>
            <?php if ($line[1] === 1): ?>
            <li style="background-color: green;">
            <?php elseif ($line[1] === -1): ?>
            <li style="background-color: red;">
            <?php else: ?>
            <li>
            <?php endif ?>
                <pre><?php echo htmlspecialchars($line[0], ENT_QUOTES, 'UTF-8') ?></pre>
            </li>
            <?php endforeach ?>
        </ol>
    </body>
</html
