<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo htmlspecialchars($file, ENT_QUOTES, 'UTF-8') ?></title>
    </head>
    <body>
        <ol>
            <?php foreach ($result as $line): ?>
            <?php if ($line[1] === 1): ?>
            <li style="background-color: green;">
            <?php elseif ($line[1] === -1): ?>
            <li style="background-color: red;">
            <?php else: ?>
            <li>
            <?php endif ?>
                <pre><?php echo htmlspecialchars($line[0], ENT_QUOTES, 'UTF-8') ?></pre>
            </li>
            <?php endforeach ?>
        </ol>
    </body>
</html
