<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo htmlspecialchars($file, ENT_QUOTES, 'UTF-8') ?></title>
        <style>

body {
    font-family: helvetica, arial, sans-serif;
}

dt, dd {
    display: inline;
}

dd {
    font-weight: bold;
    margin-right: 5em;
}

.numeric {
    text-align: right;
}

.poor {
    background-color: red;
}

.fair {
    background-color: yellow;
}

.good {
    background-color: green;
}

ol {
    max-width: 1000px;
}

ol li {
    height: 1.5em;
}

pre {
    display: inline;
}

        </style>
    </head>
    <body>
        <dl>
            <dt>Total Lines<dt>
            <dd><?php echo $result['stats']['totalLines'] ?></dd>
            <dt>Executable Lines<dt>
            <dd><?php echo $result['stats']['executableLines'] ?></dd>
            <dt>Lines Executed<dt>
            <dd><?php echo $result['stats']['linesExecuted'] ?></dd>
            <dt>Coverage<dt>
            <?php if ($result['stats']['coverage'] >= 0.9): ?>
            <dd class="good">
            <?php elseif ($result['stats']['coverage'] >= 0.6): ?>
            <dd class="fair">
            <?php else: ?>
            <dd class="poor">
            <?php endif ?>
                <?php echo number_format($result['stats']['coverage'] * 100, 1) ?>%
            </dd>
        </dl>
        <ol>
            <?php foreach ($result['lines'] as $line): ?>
            <?php if ($line[1] === 1): ?>
            <li class="good">
            <?php elseif ($line[1] === -1): ?>
            <li class="poor">
            <?php else: ?>
            <li>
            <?php endif ?>
                <pre><?php echo htmlspecialchars($line[0], ENT_QUOTES, 'UTF-8') ?></pre>
            </li>
            <?php endforeach ?>
        </ol>
    </body>
</html
