<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Code Coverage Summary</title>
    </head>
    <body>
        <dl>
            <dt>Total Lines<dt>
            <dd><?php echo $results['stats']['totalLines'] ?></dd>
            <dt>Executable Lines<dt>
            <dd><?php echo $results['stats']['executableLines'] ?></dd>
            <dt>Lines Executed<dt>
            <dd><?php echo $results['stats']['linesExecuted'] ?></dd>
            <dt>Coverage<dt>
            <dd><?php echo number_format($results['stats']['coverage'] * 100, 1) ?>%</dd>
        </dl>
        <table>
            <thead>
                <tr>
                    <th>File Name</th>
                    <th>Total</th>
                    <th>Executable</th>
                    <th>Executed</th>
                    <th>%</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results['files'] as $file => $result): ?>
                <tr>
                    <td>
                        <a href=".<?php echo htmlspecialchars($file . '.html', ENT_QUOTES, 'UTF-8') ?>">
                            <?php echo htmlspecialchars($file, ENT_QUOTES, 'UTF-8') ?>
                        </a>
                    </td>
                    <td><?php echo $result['stats']['totalLines'] ?></td>
                    <td><?php echo $result['stats']['executableLines'] ?></td>
                    <td><?php echo $result['stats']['linesExecuted'] ?></td>
                    <td><?php echo number_format($result['stats']['coverage'] * 100, 1) ?>%</td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </body>
</html>
