<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Code Coverage Summary</title>
        <style>

body, td {
    font-family: helvetica, arial, sans-serif;
}

dt, dd {
    display: inline;
}

dd {
    font-weight: bold;
    margin-right: 5em;
}

table {
    width: 100%;
    max-width: 1000px;
}

th {
    text-align: left;
}

.numeric {
    text-align: right;
}

.poor {
    background-color: red;
}

.fair {
    background-color: yellow;
}

.good {
    background-color: green;
}

        </style>
    </head>
    <body>
        <dl>
            <dt>Total Lines<dt>
            <dd><?php echo $results['stats']['totalLines'] ?></dd>
            <dt>Executable Lines<dt>
            <dd><?php echo $results['stats']['executableLines'] ?></dd>
            <dt>Lines Executed<dt>
            <dd><?php echo $results['stats']['linesExecuted'] ?></dd>
            <dt>Coverage<dt>
            <?php if ($results['stats']['coverage'] >= 0.9): ?>
            <dd class="good">
            <?php elseif ($results['stats']['coverage'] >= 0.6): ?>
            <dd class="fair">
            <?php else: ?>
            <dd class="poor">
            <?php endif ?>
                <?php echo number_format($results['stats']['coverage'] * 100, 1) ?>%
            </dd>
        </dl>
        <table>
            <thead>
                <tr>
                    <th>File Name</th>
                    <th class="numeric">Total</th>
                    <th class="numeric">Executable</th>
                    <th class="numeric">Executed</th>
                    <th class="numeric">%</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($results['files'] as $file => $result): ?>
                <tr>
                    <td>
                        <a href=".<?php echo htmlspecialchars($file . '.html', ENT_QUOTES, 'UTF-8') ?>">
                            <?php echo htmlspecialchars($file, ENT_QUOTES, 'UTF-8') ?>
                        </a>
                    </td>
                    <td class="numeric"><?php echo $result['stats']['totalLines'] ?></td>
                    <td class="numeric"><?php echo $result['stats']['executableLines'] ?></td>
                    <td class="numeric"><?php echo $result['stats']['linesExecuted'] ?></td>
                    <?php if ($result['stats']['coverage'] >= 0.9): ?>
                    <td class="numeric good">
                    <?php elseif ($result['stats']['coverage'] >= 0.6): ?>
                    <td class="numeric fair">
                    <?php else: ?>
                    <td class="numeric poor">
                    <?php endif ?>
                        <?php echo number_format($result['stats']['coverage'] * 100, 1) ?>%
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>
    </body>
</html>
